/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as OnboardingSiteRouteImport } from './routes/onboarding.site'
import { Route as OnboardingMediaRouteImport } from './routes/onboarding.media'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as OnboardingAssistantRouteImport } from './routes/onboarding.assistant'
import { Route as MarketingSiteRouteImport } from './routes/_marketing.site'
import { Route as MarketingScenariosRouteImport } from './routes/_marketing.scenarios'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingMediaRouteImport } from './routes/_marketing.media'
import { Route as MarketingIntegrationsRouteImport } from './routes/_marketing.integrations'
import { Route as MarketingFirst100RouteImport } from './routes/_marketing.first-100'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing.features'
import { Route as MarketingFaqRouteImport } from './routes/_marketing.faq'
import { Route as MarketingContactsRouteImport } from './routes/_marketing.contacts'
import { Route as MarketingCasesRouteImport } from './routes/_marketing.cases'
import { Route as MarketingAssistantRouteImport } from './routes/_marketing.assistant'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthCallbackRouteImport } from './routes/_auth.callback'
import { Route as AuthAcceptInviteRouteImport } from './routes/_auth.accept-invite'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppVisitorsRouteImport } from './routes/_app.visitors'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRuntimeRouteImport } from './routes/_app.runtime'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCallsRouteImport } from './routes/_app.calls'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAssistantsRouteImport } from './routes/_app.assistants'
import { Route as AppAppIntegrationsRouteImport } from './routes/_app.app-integrations'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AppApiKeysRouteImport } from './routes/_app.api-keys'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppKnowledgeIndexRouteImport } from './routes/_app.knowledge.index'
import { Route as MarketingScenariosNicheRouteImport } from './routes/_marketing.scenarios.$niche'
import { Route as MarketingLegalPrivacyRouteImport } from './routes/_marketing.legal.privacy'
import { Route as MarketingLegalOfferRouteImport } from './routes/_marketing.legal.offer'
import { Route as MarketingCasesSlugRouteImport } from './routes/_marketing.cases.$slug'
import { Route as AppRuntimeWorkspaceRouteImport } from './routes/_app.runtime.workspace'
import { Route as AppRuntimeOperatorRouteImport } from './routes/_app.runtime.operator'
import { Route as AppRuntimeIncidentsRouteImport } from './routes/_app.runtime.incidents'
import { Route as AppRuntimeConsistencyRouteImport } from './routes/_app.runtime.consistency'
import { Route as AppRuntimeCompareRouteImport } from './routes/_app.runtime.compare'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppKnowledgeBaseIdRouteImport } from './routes/_app.knowledge.$baseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const OnboardingSiteRoute = OnboardingSiteRouteImport.update({
  id: '/onboarding/site',
  path: '/onboarding/site',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMediaRoute = OnboardingMediaRouteImport.update({
  id: '/onboarding/media',
  path: '/onboarding/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAssistantRoute = OnboardingAssistantRouteImport.update({
  id: '/onboarding/assistant',
  path: '/onboarding/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSiteRoute = MarketingSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingScenariosRoute = MarketingScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingMediaRoute = MarketingMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingIntegrationsRoute = MarketingIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFirst100Route = MarketingFirst100RouteImport.update({
  id: '/first-100',
  path: '/first-100',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactsRoute = MarketingContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCasesRoute = MarketingCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAssistantRoute = MarketingAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitorsRoute = AppVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRuntimeRoute = AppRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantsRoute = AppAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => AppRoute,
} as any)
const AppAppIntegrationsRoute = AppAppIntegrationsRouteImport.update({
  id: '/app-integrations',
  path: '/app-integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppKnowledgeIndexRoute = AppKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKnowledgeRoute,
} as any)
const MarketingScenariosNicheRoute = MarketingScenariosNicheRouteImport.update({
  id: '/$niche',
  path: '/$niche',
  getParentRoute: () => MarketingScenariosRoute,
} as any)
const MarketingLegalPrivacyRoute = MarketingLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalOfferRoute = MarketingLegalOfferRouteImport.update({
  id: '/legal/offer',
  path: '/legal/offer',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCasesSlugRoute = MarketingCasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingCasesRoute,
} as any)
const AppRuntimeWorkspaceRoute = AppRuntimeWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRuntimeRoute,
} as any)
const AppRuntimeOperatorRoute = AppRuntimeOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AppRuntimeRoute,
} as any)
const AppRuntimeIncidentsRoute = AppRuntimeIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRuntimeRoute,
} as any)
const AppRuntimeConsistencyRoute = AppRuntimeConsistencyRouteImport.update({
  id: '/consistency',
  path: '/consistency',
  getParentRoute: () => AppRuntimeRoute,
} as any)
const AppRuntimeCompareRoute = AppRuntimeCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRuntimeRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppKnowledgeBaseIdRoute = AppKnowledgeBaseIdRouteImport.update({
  id: '/$baseId',
  path: '/$baseId',
  getParentRoute: () => AppKnowledgeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-keys': typeof AppApiKeysRoute
  '/app': typeof AppAppRoute
  '/app-integrations': typeof AppAppIntegrationsRoute
  '/assistants': typeof AppAssistantsRoute
  '/audit': typeof AppAuditRoute
  '/calls': typeof AppCallsRoute
  '/chat': typeof AppChatRoute
  '/knowledge': typeof AppKnowledgeRouteWithChildren
  '/leads': typeof AppLeadsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/runtime': typeof AppRuntimeRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/visitors': typeof AppVisitorsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof MarketingAboutRoute
  '/assistant': typeof MarketingAssistantRoute
  '/cases': typeof MarketingCasesRouteWithChildren
  '/contacts': typeof MarketingContactsRoute
  '/faq': typeof MarketingFaqRoute
  '/features': typeof MarketingFeaturesRoute
  '/first-100': typeof MarketingFirst100Route
  '/integrations': typeof MarketingIntegrationsRoute
  '/media': typeof MarketingMediaRoute
  '/pricing': typeof MarketingPricingRoute
  '/scenarios': typeof MarketingScenariosRouteWithChildren
  '/site': typeof MarketingSiteRoute
  '/onboarding/assistant': typeof OnboardingAssistantRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/site': typeof OnboardingSiteRoute
  '/knowledge/$baseId': typeof AppKnowledgeBaseIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/runtime/compare': typeof AppRuntimeCompareRoute
  '/runtime/consistency': typeof AppRuntimeConsistencyRoute
  '/runtime/incidents': typeof AppRuntimeIncidentsRoute
  '/runtime/operator': typeof AppRuntimeOperatorRoute
  '/runtime/workspace': typeof AppRuntimeWorkspaceRoute
  '/cases/$slug': typeof MarketingCasesSlugRoute
  '/legal/offer': typeof MarketingLegalOfferRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/scenarios/$niche': typeof MarketingScenariosNicheRoute
  '/knowledge/': typeof AppKnowledgeIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-keys': typeof AppApiKeysRoute
  '/app': typeof AppAppRoute
  '/app-integrations': typeof AppAppIntegrationsRoute
  '/assistants': typeof AppAssistantsRoute
  '/audit': typeof AppAuditRoute
  '/calls': typeof AppCallsRoute
  '/chat': typeof AppChatRoute
  '/leads': typeof AppLeadsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/runtime': typeof AppRuntimeRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/visitors': typeof AppVisitorsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/about': typeof MarketingAboutRoute
  '/assistant': typeof MarketingAssistantRoute
  '/cases': typeof MarketingCasesRouteWithChildren
  '/contacts': typeof MarketingContactsRoute
  '/faq': typeof MarketingFaqRoute
  '/features': typeof MarketingFeaturesRoute
  '/first-100': typeof MarketingFirst100Route
  '/integrations': typeof MarketingIntegrationsRoute
  '/media': typeof MarketingMediaRoute
  '/pricing': typeof MarketingPricingRoute
  '/scenarios': typeof MarketingScenariosRouteWithChildren
  '/site': typeof MarketingSiteRoute
  '/onboarding/assistant': typeof OnboardingAssistantRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/site': typeof OnboardingSiteRoute
  '/knowledge/$baseId': typeof AppKnowledgeBaseIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/runtime/compare': typeof AppRuntimeCompareRoute
  '/runtime/consistency': typeof AppRuntimeConsistencyRoute
  '/runtime/incidents': typeof AppRuntimeIncidentsRoute
  '/runtime/operator': typeof AppRuntimeOperatorRoute
  '/runtime/workspace': typeof AppRuntimeWorkspaceRoute
  '/cases/$slug': typeof MarketingCasesSlugRoute
  '/legal/offer': typeof MarketingLegalOfferRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/scenarios/$niche': typeof MarketingScenariosNicheRoute
  '/knowledge': typeof AppKnowledgeIndexRoute
  '/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/app': typeof AppAppRoute
  '/_app/app-integrations': typeof AppAppIntegrationsRoute
  '/_app/assistants': typeof AppAssistantsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/knowledge': typeof AppKnowledgeRouteWithChildren
  '/_app/leads': typeof AppLeadsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/runtime': typeof AppRuntimeRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/visitors': typeof AppVisitorsRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/_auth/accept-invite': typeof AuthAcceptInviteRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/assistant': typeof MarketingAssistantRoute
  '/_marketing/cases': typeof MarketingCasesRouteWithChildren
  '/_marketing/contacts': typeof MarketingContactsRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/first-100': typeof MarketingFirst100Route
  '/_marketing/integrations': typeof MarketingIntegrationsRoute
  '/_marketing/media': typeof MarketingMediaRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/scenarios': typeof MarketingScenariosRouteWithChildren
  '/_marketing/site': typeof MarketingSiteRoute
  '/onboarding/assistant': typeof OnboardingAssistantRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/site': typeof OnboardingSiteRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/knowledge/$baseId': typeof AppKnowledgeBaseIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/runtime/compare': typeof AppRuntimeCompareRoute
  '/_app/runtime/consistency': typeof AppRuntimeConsistencyRoute
  '/_app/runtime/incidents': typeof AppRuntimeIncidentsRoute
  '/_app/runtime/operator': typeof AppRuntimeOperatorRoute
  '/_app/runtime/workspace': typeof AppRuntimeWorkspaceRoute
  '/_marketing/cases/$slug': typeof MarketingCasesSlugRoute
  '/_marketing/legal/offer': typeof MarketingLegalOfferRoute
  '/_marketing/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/_marketing/scenarios/$niche': typeof MarketingScenariosNicheRoute
  '/_app/knowledge/': typeof AppKnowledgeIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/analytics'
    | '/api-keys'
    | '/app'
    | '/app-integrations'
    | '/assistants'
    | '/audit'
    | '/calls'
    | '/chat'
    | '/knowledge'
    | '/leads'
    | '/onboarding'
    | '/projects'
    | '/runtime'
    | '/settings'
    | '/team'
    | '/visitors'
    | '/workspace'
    | '/accept-invite'
    | '/callback'
    | '/login'
    | '/signup'
    | '/about'
    | '/assistant'
    | '/cases'
    | '/contacts'
    | '/faq'
    | '/features'
    | '/first-100'
    | '/integrations'
    | '/media'
    | '/pricing'
    | '/scenarios'
    | '/site'
    | '/onboarding/assistant'
    | '/onboarding/complete'
    | '/onboarding/media'
    | '/onboarding/site'
    | '/knowledge/$baseId'
    | '/projects/$projectId'
    | '/runtime/compare'
    | '/runtime/consistency'
    | '/runtime/incidents'
    | '/runtime/operator'
    | '/runtime/workspace'
    | '/cases/$slug'
    | '/legal/offer'
    | '/legal/privacy'
    | '/scenarios/$niche'
    | '/knowledge/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/analytics'
    | '/api-keys'
    | '/app'
    | '/app-integrations'
    | '/assistants'
    | '/audit'
    | '/calls'
    | '/chat'
    | '/leads'
    | '/onboarding'
    | '/runtime'
    | '/settings'
    | '/team'
    | '/visitors'
    | '/workspace'
    | '/accept-invite'
    | '/callback'
    | '/login'
    | '/signup'
    | '/about'
    | '/assistant'
    | '/cases'
    | '/contacts'
    | '/faq'
    | '/features'
    | '/first-100'
    | '/integrations'
    | '/media'
    | '/pricing'
    | '/scenarios'
    | '/site'
    | '/onboarding/assistant'
    | '/onboarding/complete'
    | '/onboarding/media'
    | '/onboarding/site'
    | '/knowledge/$baseId'
    | '/projects/$projectId'
    | '/runtime/compare'
    | '/runtime/consistency'
    | '/runtime/incidents'
    | '/runtime/operator'
    | '/runtime/workspace'
    | '/cases/$slug'
    | '/legal/offer'
    | '/legal/privacy'
    | '/scenarios/$niche'
    | '/knowledge'
    | '/projects'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_app/analytics'
    | '/_app/api-keys'
    | '/_app/app'
    | '/_app/app-integrations'
    | '/_app/assistants'
    | '/_app/audit'
    | '/_app/calls'
    | '/_app/chat'
    | '/_app/knowledge'
    | '/_app/leads'
    | '/_app/onboarding'
    | '/_app/projects'
    | '/_app/runtime'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/visitors'
    | '/_app/workspace'
    | '/_auth/accept-invite'
    | '/_auth/callback'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_marketing/about'
    | '/_marketing/assistant'
    | '/_marketing/cases'
    | '/_marketing/contacts'
    | '/_marketing/faq'
    | '/_marketing/features'
    | '/_marketing/first-100'
    | '/_marketing/integrations'
    | '/_marketing/media'
    | '/_marketing/pricing'
    | '/_marketing/scenarios'
    | '/_marketing/site'
    | '/onboarding/assistant'
    | '/onboarding/complete'
    | '/onboarding/media'
    | '/onboarding/site'
    | '/_marketing/'
    | '/_app/knowledge/$baseId'
    | '/_app/projects/$projectId'
    | '/_app/runtime/compare'
    | '/_app/runtime/consistency'
    | '/_app/runtime/incidents'
    | '/_app/runtime/operator'
    | '/_app/runtime/workspace'
    | '/_marketing/cases/$slug'
    | '/_marketing/legal/offer'
    | '/_marketing/legal/privacy'
    | '/_marketing/scenarios/$niche'
    | '/_app/knowledge/'
    | '/_app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OnboardingAssistantRoute: typeof OnboardingAssistantRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingMediaRoute: typeof OnboardingMediaRoute
  OnboardingSiteRoute: typeof OnboardingSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/onboarding/site': {
      id: '/onboarding/site'
      path: '/onboarding/site'
      fullPath: '/onboarding/site'
      preLoaderRoute: typeof OnboardingSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/media': {
      id: '/onboarding/media'
      path: '/onboarding/media'
      fullPath: '/onboarding/media'
      preLoaderRoute: typeof OnboardingMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/assistant': {
      id: '/onboarding/assistant'
      path: '/onboarding/assistant'
      fullPath: '/onboarding/assistant'
      preLoaderRoute: typeof OnboardingAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/site': {
      id: '/_marketing/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof MarketingSiteRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/scenarios': {
      id: '/_marketing/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof MarketingScenariosRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/media': {
      id: '/_marketing/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MarketingMediaRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/integrations': {
      id: '/_marketing/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof MarketingIntegrationsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/first-100': {
      id: '/_marketing/first-100'
      path: '/first-100'
      fullPath: '/first-100'
      preLoaderRoute: typeof MarketingFirst100RouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contacts': {
      id: '/_marketing/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof MarketingContactsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cases': {
      id: '/_marketing/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof MarketingCasesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/assistant': {
      id: '/_marketing/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof MarketingAssistantRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accept-invite': {
      id: '/_auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visitors': {
      id: '/_app/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AppVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runtime': {
      id: '/_app/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof AppRuntimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistants': {
      id: '/_app/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AppAssistantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app-integrations': {
      id: '/_app/app-integrations'
      path: '/app-integrations'
      fullPath: '/app-integrations'
      preLoaderRoute: typeof AppAppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/knowledge/': {
      id: '/_app/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AppKnowledgeIndexRouteImport
      parentRoute: typeof AppKnowledgeRoute
    }
    '/_marketing/scenarios/$niche': {
      id: '/_marketing/scenarios/$niche'
      path: '/$niche'
      fullPath: '/scenarios/$niche'
      preLoaderRoute: typeof MarketingScenariosNicheRouteImport
      parentRoute: typeof MarketingScenariosRoute
    }
    '/_marketing/legal/privacy': {
      id: '/_marketing/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof MarketingLegalPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/offer': {
      id: '/_marketing/legal/offer'
      path: '/legal/offer'
      fullPath: '/legal/offer'
      preLoaderRoute: typeof MarketingLegalOfferRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cases/$slug': {
      id: '/_marketing/cases/$slug'
      path: '/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof MarketingCasesSlugRouteImport
      parentRoute: typeof MarketingCasesRoute
    }
    '/_app/runtime/workspace': {
      id: '/_app/runtime/workspace'
      path: '/workspace'
      fullPath: '/runtime/workspace'
      preLoaderRoute: typeof AppRuntimeWorkspaceRouteImport
      parentRoute: typeof AppRuntimeRoute
    }
    '/_app/runtime/operator': {
      id: '/_app/runtime/operator'
      path: '/operator'
      fullPath: '/runtime/operator'
      preLoaderRoute: typeof AppRuntimeOperatorRouteImport
      parentRoute: typeof AppRuntimeRoute
    }
    '/_app/runtime/incidents': {
      id: '/_app/runtime/incidents'
      path: '/incidents'
      fullPath: '/runtime/incidents'
      preLoaderRoute: typeof AppRuntimeIncidentsRouteImport
      parentRoute: typeof AppRuntimeRoute
    }
    '/_app/runtime/consistency': {
      id: '/_app/runtime/consistency'
      path: '/consistency'
      fullPath: '/runtime/consistency'
      preLoaderRoute: typeof AppRuntimeConsistencyRouteImport
      parentRoute: typeof AppRuntimeRoute
    }
    '/_app/runtime/compare': {
      id: '/_app/runtime/compare'
      path: '/compare'
      fullPath: '/runtime/compare'
      preLoaderRoute: typeof AppRuntimeCompareRouteImport
      parentRoute: typeof AppRuntimeRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/knowledge/$baseId': {
      id: '/_app/knowledge/$baseId'
      path: '/$baseId'
      fullPath: '/knowledge/$baseId'
      preLoaderRoute: typeof AppKnowledgeBaseIdRouteImport
      parentRoute: typeof AppKnowledgeRoute
    }
  }
}

interface AppKnowledgeRouteChildren {
  AppKnowledgeBaseIdRoute: typeof AppKnowledgeBaseIdRoute
  AppKnowledgeIndexRoute: typeof AppKnowledgeIndexRoute
}

const AppKnowledgeRouteChildren: AppKnowledgeRouteChildren = {
  AppKnowledgeBaseIdRoute: AppKnowledgeBaseIdRoute,
  AppKnowledgeIndexRoute: AppKnowledgeIndexRoute,
}

const AppKnowledgeRouteWithChildren = AppKnowledgeRoute._addFileChildren(
  AppKnowledgeRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRuntimeRouteChildren {
  AppRuntimeCompareRoute: typeof AppRuntimeCompareRoute
  AppRuntimeConsistencyRoute: typeof AppRuntimeConsistencyRoute
  AppRuntimeIncidentsRoute: typeof AppRuntimeIncidentsRoute
  AppRuntimeOperatorRoute: typeof AppRuntimeOperatorRoute
  AppRuntimeWorkspaceRoute: typeof AppRuntimeWorkspaceRoute
}

const AppRuntimeRouteChildren: AppRuntimeRouteChildren = {
  AppRuntimeCompareRoute: AppRuntimeCompareRoute,
  AppRuntimeConsistencyRoute: AppRuntimeConsistencyRoute,
  AppRuntimeIncidentsRoute: AppRuntimeIncidentsRoute,
  AppRuntimeOperatorRoute: AppRuntimeOperatorRoute,
  AppRuntimeWorkspaceRoute: AppRuntimeWorkspaceRoute,
}

const AppRuntimeRouteWithChildren = AppRuntimeRoute._addFileChildren(
  AppRuntimeRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAppRoute: typeof AppAppRoute
  AppAppIntegrationsRoute: typeof AppAppIntegrationsRoute
  AppAssistantsRoute: typeof AppAssistantsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCallsRoute: typeof AppCallsRoute
  AppChatRoute: typeof AppChatRoute
  AppKnowledgeRoute: typeof AppKnowledgeRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppRuntimeRoute: typeof AppRuntimeRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppVisitorsRoute: typeof AppVisitorsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppAppRoute: AppAppRoute,
  AppAppIntegrationsRoute: AppAppIntegrationsRoute,
  AppAssistantsRoute: AppAssistantsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCallsRoute: AppCallsRoute,
  AppChatRoute: AppChatRoute,
  AppKnowledgeRoute: AppKnowledgeRouteWithChildren,
  AppLeadsRoute: AppLeadsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppRuntimeRoute: AppRuntimeRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppVisitorsRoute: AppVisitorsRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingCasesRouteChildren {
  MarketingCasesSlugRoute: typeof MarketingCasesSlugRoute
}

const MarketingCasesRouteChildren: MarketingCasesRouteChildren = {
  MarketingCasesSlugRoute: MarketingCasesSlugRoute,
}

const MarketingCasesRouteWithChildren = MarketingCasesRoute._addFileChildren(
  MarketingCasesRouteChildren,
)

interface MarketingScenariosRouteChildren {
  MarketingScenariosNicheRoute: typeof MarketingScenariosNicheRoute
}

const MarketingScenariosRouteChildren: MarketingScenariosRouteChildren = {
  MarketingScenariosNicheRoute: MarketingScenariosNicheRoute,
}

const MarketingScenariosRouteWithChildren =
  MarketingScenariosRoute._addFileChildren(MarketingScenariosRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingAssistantRoute: typeof MarketingAssistantRoute
  MarketingCasesRoute: typeof MarketingCasesRouteWithChildren
  MarketingContactsRoute: typeof MarketingContactsRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingFirst100Route: typeof MarketingFirst100Route
  MarketingIntegrationsRoute: typeof MarketingIntegrationsRoute
  MarketingMediaRoute: typeof MarketingMediaRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingScenariosRoute: typeof MarketingScenariosRouteWithChildren
  MarketingSiteRoute: typeof MarketingSiteRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingLegalOfferRoute: typeof MarketingLegalOfferRoute
  MarketingLegalPrivacyRoute: typeof MarketingLegalPrivacyRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingAssistantRoute: MarketingAssistantRoute,
  MarketingCasesRoute: MarketingCasesRouteWithChildren,
  MarketingContactsRoute: MarketingContactsRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingFirst100Route: MarketingFirst100Route,
  MarketingIntegrationsRoute: MarketingIntegrationsRoute,
  MarketingMediaRoute: MarketingMediaRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingScenariosRoute: MarketingScenariosRouteWithChildren,
  MarketingSiteRoute: MarketingSiteRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingLegalOfferRoute: MarketingLegalOfferRoute,
  MarketingLegalPrivacyRoute: MarketingLegalPrivacyRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OnboardingAssistantRoute: OnboardingAssistantRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingMediaRoute: OnboardingMediaRoute,
  OnboardingSiteRoute: OnboardingSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
