/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingFirst100RouteImport } from './routes/_marketing.first-100'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing.features'
import { Route as MarketingIntegrationsRouteImport } from './routes/_marketing.integrations'
import { Route as MarketingCasesRouteImport } from './routes/_marketing.cases'
import { Route as MarketingCasesSlugRouteImport } from './routes/_marketing.cases.$slug'
import { Route as MarketingScenariosRouteImport } from './routes/_marketing.scenarios'
import { Route as MarketingScenariosNicheRouteImport } from './routes/_marketing.scenarios.$niche'
import { Route as MarketingFaqRouteImport } from './routes/_marketing.faq'
import { Route as MarketingContactsRouteImport } from './routes/_marketing.contacts'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as MarketingLegalPrivacyRouteImport } from './routes/_marketing.legal.privacy'
import { Route as MarketingLegalOfferRouteImport } from './routes/_marketing.legal.offer'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthCallbackRouteImport } from './routes/_auth.callback'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFirst100Route = MarketingFirst100RouteImport.update({
  id: '/first-100',
  path: '/first-100',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingIntegrationsRoute = MarketingIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCasesRoute = MarketingCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCasesSlugRoute = MarketingCasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingScenariosRoute = MarketingScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingScenariosNicheRoute = MarketingScenariosNicheRouteImport.update({
  id: '/scenarios/$niche',
  path: '/scenarios/$niche',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactsRoute = MarketingContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalPrivacyRoute = MarketingLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalOfferRoute = MarketingLegalOfferRouteImport.update({
  id: '/legal/offer',
  path: '/legal/offer',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppAppRoute
  '/first-100': typeof MarketingFirst100Route
  '/pricing': typeof MarketingPricingRoute
  '/features': typeof MarketingFeaturesRoute
  '/integrations': typeof MarketingIntegrationsRoute
  '/cases': typeof MarketingCasesRoute
  '/cases/$slug': typeof MarketingCasesSlugRoute
  '/scenarios': typeof MarketingScenariosRoute
  '/scenarios/$niche': typeof MarketingScenariosNicheRoute
  '/faq': typeof MarketingFaqRoute
  '/contacts': typeof MarketingContactsRoute
  '/about': typeof MarketingAboutRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/offer': typeof MarketingLegalOfferRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppAppRoute
  '/first-100': typeof MarketingFirst100Route
  '/pricing': typeof MarketingPricingRoute
  '/features': typeof MarketingFeaturesRoute
  '/integrations': typeof MarketingIntegrationsRoute
  '/cases': typeof MarketingCasesRoute
  '/cases/$slug': typeof MarketingCasesSlugRoute
  '/scenarios': typeof MarketingScenariosRoute
  '/scenarios/$niche': typeof MarketingScenariosNicheRoute
  '/faq': typeof MarketingFaqRoute
  '/contacts': typeof MarketingContactsRoute
  '/about': typeof MarketingAboutRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/offer': typeof MarketingLegalOfferRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/app': typeof AppAppRoute
  '/_marketing/first-100': typeof MarketingFirst100Route
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/integrations': typeof MarketingIntegrationsRoute
  '/_marketing/cases': typeof MarketingCasesRoute
  '/_marketing/cases/$slug': typeof MarketingCasesSlugRoute
  '/_marketing/scenarios': typeof MarketingScenariosRoute
  '/_marketing/scenarios/$niche': typeof MarketingScenariosNicheRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/contacts': typeof MarketingContactsRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/_marketing/legal/offer': typeof MarketingLegalOfferRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/first-100'
    | '/pricing'
    | '/features'
    | '/integrations'
    | '/cases'
    | '/cases/$slug'
    | '/scenarios'
    | '/scenarios/$niche'
    | '/faq'
    | '/contacts'
    | '/about'
    | '/legal/privacy'
    | '/legal/offer'
    | '/login'
    | '/signup'
    | '/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/first-100'
    | '/pricing'
    | '/features'
    | '/integrations'
    | '/cases'
    | '/cases/$slug'
    | '/scenarios'
    | '/scenarios/$niche'
    | '/faq'
    | '/contacts'
    | '/about'
    | '/legal/privacy'
    | '/legal/offer'
    | '/login'
    | '/signup'
    | '/callback'
  id:
    | '__root__'
    | '/_marketing'
    | '/_auth'
    | '/_app'
    | '/_app/app'
    | '/_marketing/first-100'
    | '/_marketing/pricing'
    | '/_marketing/features'
    | '/_marketing/integrations'
    | '/_marketing/cases'
    | '/_marketing/cases/$slug'
    | '/_marketing/scenarios'
    | '/_marketing/scenarios/$niche'
    | '/_marketing/faq'
    | '/_marketing/contacts'
    | '/_marketing/about'
    | '/_marketing/legal/privacy'
    | '/_marketing/legal/offer'
    | '/_marketing/'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/first-100': {
      id: '/_marketing/first-100'
      path: '/first-100'
      fullPath: '/first-100'
      preLoaderRoute: typeof MarketingFirst100RouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/integrations': {
      id: '/_marketing/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof MarketingIntegrationsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cases': {
      id: '/_marketing/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof MarketingCasesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cases/$slug': {
      id: '/_marketing/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof MarketingCasesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/scenarios': {
      id: '/_marketing/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof MarketingScenariosRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/scenarios/$niche': {
      id: '/_marketing/scenarios/$niche'
      path: '/scenarios/$niche'
      fullPath: '/scenarios/$niche'
      preLoaderRoute: typeof MarketingScenariosNicheRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contacts': {
      id: '/_marketing/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof MarketingContactsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/privacy': {
      id: '/_marketing/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof MarketingLegalPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/offer': {
      id: '/_marketing/legal/offer'
      path: '/legal/offer'
      fullPath: '/legal/offer'
      preLoaderRoute: typeof MarketingLegalOfferRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingFirst100Route: typeof MarketingFirst100Route
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingIntegrationsRoute: typeof MarketingIntegrationsRoute
  MarketingCasesRoute: typeof MarketingCasesRoute
  MarketingCasesSlugRoute: typeof MarketingCasesSlugRoute
  MarketingScenariosRoute: typeof MarketingScenariosRoute
  MarketingScenariosNicheRoute: typeof MarketingScenariosNicheRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingContactsRoute: typeof MarketingContactsRoute
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingLegalPrivacyRoute: typeof MarketingLegalPrivacyRoute
  MarketingLegalOfferRoute: typeof MarketingLegalOfferRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingFirst100Route: MarketingFirst100Route,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingIntegrationsRoute: MarketingIntegrationsRoute,
  MarketingCasesRoute: MarketingCasesRoute,
  MarketingCasesSlugRoute: MarketingCasesSlugRoute,
  MarketingScenariosRoute: MarketingScenariosRoute,
  MarketingScenariosNicheRoute: MarketingScenariosNicheRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingContactsRoute: MarketingContactsRoute,
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingLegalPrivacyRoute: MarketingLegalPrivacyRoute,
  MarketingLegalOfferRoute: MarketingLegalOfferRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
